model_name: "BAAI/bge-reranker-v2-m3"
eval_path: "evaluation-result/me5_v2_hybrid.json"
corpus_path: "ir-datasets/v2/corpus.json"
log_path: "evaluation-result/bge_m3_ranker_v2_metrics_v5.csv"
save_path: "evaluation-result/bge_m3_ranker_v2_metrics_v5.json"
max_length: 512
batch_size: 64